version: '3.9'
services:
  app-gama:
    build:
      context: .
      dockerfile: applications/app-gama/Dockerfile
    ports:
      - '8082:8082'
    depends_on:
        - rabbitmq
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
networks:
  mynetwork:
