version: '3.9'
services:
  beta:
    container_name: beta
    image: beta:v1.0.1
    ports:
      - '8081'
    depends_on:
        - rabbitmq
        - mysql
    networks:
      - mynetwork

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - mynetwork
  mysql:
    image: mysql:8
    volumes:
      - D:\Docker-Volumes:/etc/mysql
    ports:
      - "3306:3306"
networks:
  mynetwork:
