beta: 8081
gama: 8082
server:
  port: 8080
spring:
  r2dbc:
    url: "r2dbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false"
    #url: "r2dbc:mysql://localhost:3306/prueba1"
    #url: "r2dbc:mysql://mysql:3306/prueba1"
    username: ${DB_USERNAME}
    #username: "root"
    password: ${DB_PASSWORD}
    #password: "d04m07a1997"
  application:
    name: "Inventory"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  data:
    mongodb:
      host: mongodb-service
      port: 27017
      database: test3
      #uri: "mongodb://localhost:27017/test3"
      #uri: "mongodb://mongodb:27017/test3"
  rabbitmq:
    host: "rabbitmq-service"
    #host: "localhost"
    #host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: /
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
