apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  selector:
    matchLabels:
      app: app-service-k8s-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: app-service-k8s-mysql
    spec:
      containers:
        - name: app-service-k8s
          image: dapevi1997/app-service:ku1
          ports:
            - containerPort: 8080
          env:   # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              value : mysql


            - name: DB_NAME  # Setting Database name from configMap
              value : prueba1

            - name: DB_USERNAME  # Setting Database username from Secret
              value : root

            - name: DB_PASSWORD # Setting Database password from Secret
              value : d04m07a1997


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: app-service-svc
spec:
  selector:
    app: app-service-k8s-mysql
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.