server:
  port: 8081
spring:
  r2dbc:
    url: "r2dbc:mysql://localhost:3306/prueba1"
    username: "root"
    password: "d04m07a1997"
  application:
    name: "Inventory"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  rabbitmq:
    host: "localhost"
    username: "guest"
    password: "guest"
    virtual-host: /
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

