server:
  port: 8081
spring:
  r2dbc:
    #url: "r2dbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false"
    url: "r2dbc:mysql://localhost:3306/prueba1"
    #url: "r2dbc:mysql://mysql:3306/prueba1"
    #username: ${DB_USERNAME}
    username: "root"
    #password: ${DB_PASSWORD}
    password: "d04m07a1997"
  application:
    name: "Inventory"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb://localhost:27017/test3"
  rabbitmq:
    host: "localhost"
    #host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: /
    port: 5672

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
